init:
	@echo "初期設定を開始します"
	docker compose build

start:
	@echo "コンテナを立ち上げます"
	docker compose up

down:
	@echo "コンテナを落とします"
	docker compose down
	
go:
	@echo "コンテナの中に入ります"
	docker compose exec go bash
